version: "3"

services:
  db:
    restart: always
    image: postgres
    container_name: jobtracker #you can change this
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
    ports:
      - "1234:1234"
    expose:
      - 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    container_name: job-pgadmin #you can change this
    depends_on:
      - db
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: root
    restart: always
      
  rest_api:
    container_name: django_rest_api
    build:
      context: .
      dockerfile: DockerfilePython
    command: ./run-migrate-and-server.sh
    volumes:
      - ./code/django_rest_api:/code
    tty: true
    ports:
      - 8080:8080
    expose:
      - 8080
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
  # web_front:
  #   container_name: django_web_front1
  #   build:
  #     context: .
  #     dockerfile: DockerfileNode
  #   command: ./npm-install-and-start.sh 
  #   volumes:
  #     - ./code/django_web_front1:/code
  #   tty: true
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - rest_api
volumes:
  postgres_data: