# Generated by Django 2.1.7 on 2022-10-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobdatabase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('company', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=800)),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
