# Generated by Django 2.1.7 on 2022-10-17 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobdatabase', '0002_auto_20221014_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('salary_min', models.IntegerField()),
                ('salary_max', models.IntegerField()),
                ('type', models.IntegerField()),
                ('worktype', models.IntegerField()),
                ('jd', models.TextField()),
                ('prefer_status', models.IntegerField()),
                ('applicants', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=80)),
            ],
        ),
        migrations.DeleteModel(
            name='JobInfo',
        ),
    ]
