# Generated by Django 2.1.7 on 2022-10-17 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobdatabase', '0003_auto_20221017_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('service', models.CharField(max_length=80)),
                ('link', models.CharField(max_length=80)),
                ('employes_start', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=80)),
                ('link', models.CharField(max_length=80)),
                ('company_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jobdatabase.Company')),
            ],
        ),
        migrations.CreateModel(
            name='JobState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('date', models.DateField()),
                ('job_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jobdatabase.JobList')),
                ('user_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jobdatabase.User')),
            ],
        ),
        migrations.AddField(
            model_name='notes',
            name='job_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jobdatabase.JobList'),
        ),
        migrations.AddField(
            model_name='joblist',
            name='company_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jobdatabase.Company'),
        ),
    ]
