# Generated by Django 2.1.7 on 2022-10-17 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usercontrol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('service', models.CharField(max_length=80)),
                ('link', models.CharField(max_length=80)),
                ('employes_start', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=80)),
                ('link', models.CharField(max_length=80)),
                ('company_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jobtracking.Company')),
            ],
        ),
        migrations.CreateModel(
            name='JobList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('salary_min', models.IntegerField()),
                ('salary_max', models.IntegerField()),
                ('type', models.IntegerField()),
                ('worktype', models.IntegerField()),
                ('jd', models.TextField()),
                ('prefer_status', models.IntegerField()),
                ('applicants', models.IntegerField()),
                ('company_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jobtracking.Company')),
            ],
        ),
        migrations.CreateModel(
            name='JobState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('date', models.DateField()),
                ('job_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jobtracking.JobList')),
                ('user_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='usercontrol.User')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=80)),
                ('job_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jobtracking.JobList')),
            ],
        ),
    ]
